# spring.datasource.url:jdbc:h2:mem:testdb
# spring.jpa.hibernate.ddl-auto:update
# logging.level.org.springframework:DEBUG
# pagination yapmak icin parametreler
# JsonView kullanimi icin
# spring.jackson.mapper.DEFAULT_VIEW_INCLUSION:true
# persistence tarafinda validation yapmamasi
spring: 
  data: 
    web: 
      pageable: 
        default-page-size: 10
        max-page-size: 100
        page-parameter: page
        size-parameter: size
  jpa: 
    properties: 
      javax: 
        persistence: 
          validation: 
            mode: none
  profiles:
    active: 
      dev
hoaxify:
 upload-path: picture-storage
---
spring:
 profiles: product
hoaxify:
 upload-path: storage-product
---
spring:
 profiles: dev
hoaxify:
 upload-path: storage-dev
